export const DEFAULT_STALE_TRACE_TIMEOUT_MS = 5 * 60 * 1000;
export const DEFAULT_STALE_SWEEP_INTERVAL_MS = 60 * 1000;
export const DEFAULT_FLUSH_RETRY_COUNT = 2;
export const DEFAULT_FLUSH_RETRY_BASE_DELAY_MS = 250;
export const MAX_FLUSH_RETRY_DELAY_MS = 5000;
export const OPIK_PLUGIN_ID = "opik-openclaw";
export const OPIK_CREATED_FROM = "openclaw";

export const LOCAL_ATTACHMENT_UPLOAD_MAGIC_ID = "BEMinIO";
export const ATTACHMENT_UPLOAD_PART_SIZE_BYTES = 8 * 1024 * 1024;
export const DEFAULT_ATTACHMENT_BASE_URL = "https://www.comet.com/opik/api";
export const DEFAULT_UPLOADED_ATTACHMENT_CACHE_MAX_KEYS = 2048;
export const SUBAGENT_SPAN_HOSTS_MAX = 1000;
export const ATTACHMENT_UPLOADS_ENABLED = true;
export const FINALIZE_FALLBACK_TIMEOUT_MS = 100;
